MVCCoreContactForm/Models/ContactFormModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;

namespace MVCCoreContactForm.Models
{
    public class ContactFormModel
    {
        [StringLength(100, MinimumLength = 1)]
        [Required]
        public string firstName { get; set; }

        [StringLength(100, MinimumLength = 1)]
        [Required]
        public string lastName { get; set; }

        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [Required]
        public string email { get; set; }

        [Required]
        public string message { get; set; }

        public void postData()
        {
            using StreamWriter file = new StreamWriter("FormOutput.csv", append: true);
            string data = $"{this.firstName}, {this.lastName}, {this.email}, {this.message}";

            file.WriteLine(data);
        }
    }
}

MVCCoreContactForm/Models/ErrorViewModel.cs
using System;

namespace MVCCoreContactForm.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCCoreContactForm/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCCoreContactForm.Models;

namespace MVCCoreContactForm.Controllers
{
    public class ContactUsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(ContactFormModel form)
        {
            form.postData();

            return RedirectToAction("Index", "Home");
        }
    }
}

MVCCoreContactForm/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCCoreContactForm.Models;

namespace MVCCoreContactForm.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

MVCCoreContactForm/Views/ContactUs/Index.cshtml
@model MVCCoreContactForm.Models.ContactFormModel

@{
    ViewData["Title"] = "Contact Us";
}
<head>
    <link rel="stylesheet" href="~/css/ContactUs.css" />
</head>
<body>
    @using (Html.BeginForm("Index", "ContactUs", FormMethod.Post))
    {
        <div class="contactContainer">
            <h1 class="contactH1">Contact Us Form</h1>

            <div class="contactDiv">
                <label for="firstName" class="contactLabel">First Name</label>
                @Html.TextBoxFor(m => m.firstName, new { @class = "contactInput" })
                <span asp-validation-for="firstName" class="errorText"></span>
            </div>

            <div class="contactDiv">
                <label for="lastName" class="contactLabel">Last Name</label>
                @Html.TextBoxFor(m => m.lastName, new { @class = "contactInput" })
                <span asp-validation-for="lastName" class="errorText"></span>
            </div>

            <div class="contactDiv">
                <label for="email" class="contactLabel">Email</label>
                @Html.TextBoxFor(m => m.email, new { @class = "contactInput" })
                <span asp-validation-for="email" class="errorText"></span>
            </div>

            <div class="contactDiv">
                <label for="message" class="contactLabel">Message</label>
                @Html.TextAreaFor(m => m.message, new { @class = "contactTextArea" })
                <span asp-validation-for="message" class="errorText"></span>
            </div>

            <button class="contactSubmit" type="submit">SUBMIT</button>
        </div>
    }
</body>

MVCCoreContactForm/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Tech Assessment Home";
}
<head>
	<link rel="stylesheet" href="~/css/ContactUs.css" />
</head>
<body>
    <div class="contactContainer">
        <h1 class="contactH1">Hi Bizstream.</h1>

        <p class="homeText">The hyperlink below will take you to the Contact Us form. Output is written to FormOutput.csv at the root directory.</p>
        <a class="homeText" href="/ContactUs">Go to Contact Us form.</a>
    </div>
</body>

MVCCoreContactForm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>